---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: rtp-complete-case-glue
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: rtp-complete-case-glue@sha256:e58da9378cb154bed2e2e5a258debba0d0bb48263fd1a4718bc4e1e94e649310
        namespace: rtp-reference
      name: 1.0.0.0
