---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    expose: "true"
    app: rtp-complete-case-glue
    provider: fabric8
    version: 1.0.0.0
    group: rtp.demo
  name: rtp-complete-case-glue
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: rtp-complete-case-glue
